config/routes.rb
Rails.application.routes.draw do
  get "sessions/logout"
  get "sessions/omniauth"
  get "users/show"
  # get "welcome/index"
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  #
  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  #
  # # Defines the root path route ("/")
  # # root "posts#index"
  root "welcome#index"
  get "welcome/index", to: "welcome#index", as: "welcome"

  get "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#omniauth"
  get "/auth/failure", to: "sessions#failure", as: "failure"
  get "users/manage", to: "users#manage", as: "manage_users"
  patch "users/update_admin_status", to: "users#update_admin_status", as: "update_admin_status"
  delete "users/:id", to: "users#destroy", as: "delete_user"

  resources :run_time_objects do
    resources :images do
      member do
        get :download
      end
    end
  end

  resources :run_time_objects do
    resources :images do
      post "rescan", on: :member
    end
  end

  resources :run_time_objects do
    member do
      get :share
      post :share_with_users
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  has_many :run_time_objects, dependent: :destroy
  has_many :run_time_objects_permissions, dependent: :destroy
  has_many :shared_run_time_objects, through: :run_time_objects_permissions, source: :run_time_object
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_admin!

    def authenticate_admin!
        unless @current_user&.admin?
          redirect_to root_path, alert: "You are not authorized to access this page."
        end
    end

    def manage
      @display_users_admin_screen = User.where.not(id: current_user.id)
    end

    def update_admin_status
        admin_user_ids = params[:admin_user_ids] || []

        block_user_ids = params[:block_user_ids] || []

        User.where.not(id: current_user.id).find_each do |user|
          user.update(admin: admin_user_ids.include?(user.id.to_s))
        end

        User.where.not(id: current_user.id).find_each do |user|
          user.update(block: block_user_ids.include?(user.id.to_s))
        end

        redirect_to root_path, notice: "User statuses updated successfully."
    end

    def destroy
      user = User.find(params[:id])
      user.destroy
      redirect_to manage_users_path, notice: "User deleted successfully."
    end
end

app/views/users/manage.html.erb
<h1>Manage Users</h1>

<%= form_with url: update_admin_status_path, method: :patch do %>
  <table class="user-table">
    <thead>
      <tr>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Admin</th>
        <th>Block</th>

      </tr>
    </thead>

    <tbody>
      <% @display_users_admin_screen.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td>
            <%= check_box_tag 'admin_user_ids[]', user.id, user.admin? %>
          </td>
          <td>
          <%= check_box_tag 'block_user_ids[]', user.id, user.block? %>
        </td>


        </tr>
      <% end %>
    </tbody>
  </table>
  <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
  <div style="text-align: center;">
    <%= submit_tag 'Update', class: 'index-page-button'%>
    <%= link_to 'Back', root_path, class: 'index-page-button' %>
    </div>
    </div>
  
<% end %>

<style>
  :root {
    font-size: 1.6rem;
  }

  .user-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 2rem;
  }

  .user-table th,
  .user-table td {
    padding: 1rem 1.2rem;
    text-align: left;
  }

  .user-table th {
    background-color: black;
    color: white;
    font-size: 1rem;
  }

  .user-table tr:nth-child(even) {
    background-color: #f2f2f2;
  }

  .user-table tr:hover {
    background-color: #ddd;
  }

  .user-table td input[type="checkbox"] {
    transform: scale(1.5);
    cursor: pointer;
  }



  .user-table td.centered {
    display: flex;
    justify-content: center;
    align-items: center;
  }




  @media (max-width: 76.8rem) {
    .user-table th, .user-table td {
      font-size: 0.875rem;
      padding: 0.8rem;
    }


    .user-table td input[type="checkbox"] {
      transform: scale(1.3);
    }
  }
</style>