config/routes.rb
Rails.application.routes.draw do
  get "sessions/logout"
  get "sessions/omniauth"
  get "users/show"
  # get "welcome/index"
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  #
  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  #
  # # Defines the root path route ("/")
  # # root "posts#index"
  root "welcome#index"
  get "welcome/index", to: "welcome#index", as: "welcome"

  get "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#omniauth"
  get "/auth/failure", to: "sessions#failure", as: "failure"
  get "users/manage", to: "users#manage", as: "manage_users"
  patch "users/update_admin_status", to: "users#update_admin_status", as: "update_admin_status"
  delete "users/:id", to: "users#destroy", as: "delete_user"

  resources :run_time_objects do
    resources :images do
      member do
        get :download
      end
    end
  end

  resources :run_time_objects do
    resources :images do
      post "rescan", on: :member
    end
  end

  resources :run_time_objects do
    member do
      get :share
      post :share_with_users
    end
  end
end

app/views/shared/_display_flash.html.erb
<div id="flash">
  <% if flash[:alert] %>
    <p style="color: red;"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p style="color: green;"><%= flash[:notice] %></p>
  <% end %>
</div>

app/views/shared/_profile_account.html.erb
<style>
.dropdownMenu {
  position: absolute; 
  right: 5%; 
  top: 100%; 
  margin-right: 1rem;
  border-radius: 1rem;
  background-color: white; 
  z-index: 1000; 
  display: none; 
  width: 20rem; 
  box-shadow: 0 0.2rem .5rem rgba(0, 0, 0, 0.2); 
  border: 0.2rem solid black; 
  padding: 1rem;
}

.menu-link {
  display: inline-block;
  color: black;
  text-decoration: none;
  text-align: center;
  font-family: 'Noto Sans', sans-serif;
}

.menu-link:hover {
  color: lightgrey;
}

.profile-test {
  display: inline-block;
  color: black;
  text-decoration: none;
  text-align: center;
  font-family: 'Noto Sans', sans-serif;
}


</style>


<div style="position: relative;">
  <button id="dropdownButton" onclick="toggleMenu()" class="round-button">&#9776;</button>
  <div id="dropdownMenu" class="dropdownMenu">
    <p class="profile-test">
    <%= "#{@current_user.first_name} #{@current_user.last_name}" %>
    <% if @current_user.admin %>
      (Admin)
    <% end %>
    <br/>
    </p>

    <% if @current_user.admin %>
      <div style="border-top: 0.1rem solid lightgrey; margin: 0.1rem 0;"></div>
      <%= link_to 'Manage Users', manage_users_path, method: :get, class: 'menu-link' %>
    <% end %>
    <div style="border-top: 0.2rem solid lightgrey; margin: 0.2rem 0;"></div>
    <%= link_to 'Logout', logout_path, method: :get, class: 'menu-link' %>
  </div>
</div>


<script>
function toggleMenu() {
  const menu = document.getElementById('dropdownMenu');
  if (menu.style.display === 'block') {
    menu.style.display = 'none';  
  } else {
    menu.style.display = 'block';  
  }
}

window.onclick = function(event) {
  if (!event.target.matches('#dropdownButton')) {
    const menu = document.getElementById('dropdownMenu');
    if (menu.style.display === 'block') {
      menu.style.display = 'none';
    }
  }
}
</script>