config/routes.rb
Rails.application.routes.draw do
  get "sessions/logout"
  get "sessions/omniauth"
  get "users/show"
  # get "welcome/index"
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  #
  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  #
  # # Defines the root path route ("/")
  # # root "posts#index"
  root "welcome#index"
  get "welcome/index", to: "welcome#index", as: "welcome"

  get "/logout", to: "sessions#logout", as: "logout"
  get "/auth/google_oauth2/callback", to: "sessions#omniauth"
  get "/auth/failure", to: "sessions#failure", as: "failure"
  get "users/manage", to: "users#manage", as: "manage_users"
  patch "users/update_admin_status", to: "users#update_admin_status", as: "update_admin_status"
  delete "users/:id", to: "users#destroy", as: "delete_user"

  resources :run_time_objects do
    resources :images do
      member do
        get :download
      end
    end
  end

  resources :run_time_objects do
    resources :images do
      post "rescan", on: :member
    end
  end

  resources :run_time_objects do
    member do
      get :share
      post :share_with_users
    end
  end
end

app/models/run_time_object.rb
class RunTimeObject < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :run_time_objects_permissions, dependent: :destroy
  has_many :shared_users, through: :run_time_objects_permissions, source: :user, dependent: :destroy

  validates :name, presence: true
end

app/controllers/run_time_objects_controller.rb
class RunTimeObjectsController < ApplicationController
  before_action :set_run_time_object, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_share_permission, only: [ :share ]
  before_action :authorize_edit_permission, only: [ :edit, :update ]

  # GET /run_time_objects
  def index
    if @current_user.admin
      @run_time_objects = RunTimeObject.all
    else
      owned_objects = RunTimeObject.where(user_id: @current_user.id)

      shared_ids = RunTimeObject.joins(:run_time_objects_permissions)
                              .where(run_time_objects_permissions: { user_id: @current_user.id })
                              .select(:id)

      @run_time_objects = RunTimeObject.where(user_id: @current_user.id)
                                      .or(RunTimeObject.where(id: shared_ids))
    end

    @pagy, @run_time_objects = pagy(@run_time_objects)
  end

  # GET /run_time_objects/:id
  def show
    redirect_to run_time_object_images_path(@run_time_object)
  end


  # GET /run_time_objects/new
  def new
    @run_time_object = RunTimeObject.new
  end

  # POST /run_time_objects
  def create
    @run_time_object = RunTimeObject.new(run_time_object_params)
    @run_time_object.user = current_user

    if @run_time_object.save
      redirect_to @run_time_object
    else
      render :new
    end
  end

  def destroy
    @run_time_object = RunTimeObject.find(params[:id])
    if @run_time_object.user == current_user || @current_user.admin
      ActiveRecord::Base.transaction do
        begin
          @run_time_object.destroy!
          flash[:success] = "Runtime object was successfully deleted."
          redirect_to run_time_objects_path
        rescue ActiveRecord::RecordNotDestroyed => e
          flash[:error] = "There was an error deleting the runtime object: #{e.message}"
          redirect_to @run_time_object
        end
      end
    end
  end

  # GET /run_time_objects/:id/edit
  def edit
    # The @run_time_object is already set by the before_action
  end

  # PATCH/PUT /run_time_objects/:id
  def update
    if @run_time_object.update(run_time_object_params)
      flash[:success] = "Runtime object was successfully updated."
      redirect_to @run_time_object
    end
  end
  def share
    @run_time_object = RunTimeObject.find(params[:id])
    @users = User.where.not(id: @run_time_object.user_id)
    @view_permitted_user_ids = @run_time_object.run_time_objects_permissions.where(permission: "r").pluck(:user_id)
    @edit_permitted_user_ids = @run_time_object.run_time_objects_permissions.where(permission: "e").pluck(:user_id)
  end

  def share_with_users
    @run_time_object = RunTimeObject.find(params[:id])
    selected_permission_user_ids = params[:permissions] || []

    @run_time_object
      .run_time_objects_permissions
      .where.not(user_id: selected_permission_user_ids)
      .destroy_all

    selected_permission_user_ids.each do |user_id, permission_type|
      permission = @run_time_object.run_time_objects_permissions.find_or_initialize_by(user_id: user_id)

      if permission_type == "view"
        permission.permission = "r"  # 'r' means view
      elsif permission_type == "edit"
        permission.permission = "e"  # 'e' means edit
      end
      permission.save
    end

    redirect_to @run_time_object
  end

  private

  def authorize_share_permission
    @run_time_object = RunTimeObject.find(params[:id])
    user_obj = User.find(session[:user_id])
    if !user_obj.admin? && @run_time_object.user.id != user_obj.id
      flash[:alert] = "You are not authorized to share this run time object."
      redirect_to run_time_objects_path
    end
  end

  def authorize_edit_permission
    @run_time_object = RunTimeObject.find(params[:id])
    user_obj = User.find(session[:user_id])
    unless user_obj.admin? || @run_time_object.user == user_obj || @run_time_object.run_time_objects_permissions.exists?(user_id: user_obj.id, permission: "e")
      flash[:alert] = "You are not authorized to edit this object."
      redirect_to run_time_objects_path
    end
  end

  # Set the RunTimeObject for the actions
  def set_run_time_object
    @run_time_object = RunTimeObject.find(params[:id])
  end

  def run_time_object_params
    params.require(:run_time_object).permit(:name, :description)
  end
end

app/helpers/run_time_objects_helper.rb
module RunTimeObjectsHelper
end

app/helpers/runtime_objects_helper.rb
module RuntimeObjectsHelper
end

app/views/run_time_objects/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Container Image</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all" %>
</head>
<body>
  <div class="index-page-container">
    <div class="back-button">
      <%= link_to run_time_object_path(@run_time_object), class: "index-page-button" do %>
      <i class="fas fa-arrow-left"></i> Go Back
      <% end %>
    </div>
    <p class="heading">Edit Container Image</p>
    <%= form_with model: @run_time_object, url: run_time_object_path(@run_time_object), method: :patch, local: true do |form| %>
      <div class="form-container">
        <div class="form-group">
          <%= form.label :name, "Name:", class: "form-label" %>
          <%= @run_time_object.name %>
        </div>
        <div class="form-group">
          <%= form.label :description, "Description", class: "form-label" %>
          <%= form.text_area :description, class: "form-control-description", placeholder: "Value" %>
        </div>
        <div class="actions">
          <%= form.submit "Update", class: "index-page-button" %>
        </div>
    <% end %>
    </div>
  </div>

<% if @run_time_object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@run_time_object.errors.count, "error") %> prohibited this image from being saved:</h2>
    <ul>
      <% @run_time_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</body>
</html>

app/views/run_time_objects/index.html.erb
<style>
.tooltip-container {
    position: relative;
    display: inline-block;
}

.tooltip-text {
    visibility: hidden;
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 0.5rem;
    border-radius: 0.4rem;
    position: absolute;
    bottom: 100%; 
    left: 50%;
    transform: translateX(-50%);
    opacity: 0;
    transition: opacity 0.3s;
    white-space: nowrap; 
    z-index: 1;
    width: 10rem; 
    word-wrap: break-word;  
    white-space: normal;  
    overflow: hidden;  
}


.btn-create {
    padding: 0.1rem 0.2rem;
    text-decoration: none;
    border-radius: 0.5rem;
    transition: background-color 0.3s, opacity 0.3s;
}

.btn-create:hover {
    background-color: #d3d3d3; 
    opacity: 0.85; 
}
</style>

<body>
    <div class="index-page-container">
        <p class="heading">My Containers</p>
        <div class="create-button-container">
					<div class="tooltip-container">
					<%= link_to new_run_time_object_path, class: "index-page-button" do %>
					<i class="fas fa-plus-circle"></i>
					Create New Container
					<% end %>
					<span class="tooltip-text">Create a new container image</span>
					</div>
      </div>
        <div class="image-list">
            <% if @run_time_objects.present? %>
                <% @run_time_objects.each do |object| %>
                    <div class="image-tile">
                        <div class="image-content">
                            <p>
                                <%= link_to object.name, run_time_object_images_path(run_time_object_id: object.id) %>
                                <% if @current_user.admin %>
                                    <% if @current_user == object.user %>
                                        (Created By: You)
                                    <%else%>
                                        (Created By: <%= "#{object.user.first_name} #{object.user.last_name}" %>)
                                    <%end%>
                                <%end %>
                                <% if object.user_id.present? && object.user_id != @current_user.id  && !@current_user.admin%>
                                    (Shared By: <%= "#{object.user.first_name} #{object.user.last_name}" %>)
                                <% end %>
                            </p>
                        </div>
                    </div>
                <% end %>
            <% else %>
                <p>No runtime objects found for this user.</p>
            <% end %>
        </div>
    </div>
    <div class="pagy-create-image">
        <% if @pagy.pages > 1 %>
            <div class="pagy-nav">
                <%== pagy_nav(@pagy) %>
            </div>
        <% end %>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function() {  
    const tooltipContainers = document.querySelectorAll('.tooltip-container');
    
    tooltipContainers.forEach(container => {
        let hoverTimeout;
        let tooltip = container.querySelector('.tooltip-text');

        container.addEventListener('mouseenter', () => {
            clearTimeout(hoverTimeout);
            hoverTimeout = setTimeout(() => {
                tooltip.style.visibility = 'visible';
                tooltip.style.opacity = '0.85';
            }, 1000);  
        });

        container.addEventListener('mouseleave', () => {
            clearTimeout(hoverTimeout);
            tooltip.style.visibility = 'hidden';
            tooltip.style.opacity = '0';
        });
    });
});


    </script>
</body>

app/views/run_time_objects/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Container Image</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
</head>
<style>
    .tooltip-container {
        position: relative;
        display: inline-block;
        margin: 0 5px;
    }

    .tooltip-text {
        visibility: hidden;
        background-color: #333;
        color: #fff;
        text-align: center;
        padding: 0.5rem;
        border-radius: 0.4rem;
        position: absolute;
        bottom: 120%;
        left: 50%;
        transform: translateX(-50%);
        opacity: 0;
        transition: opacity 0.3s;
        white-space: nowrap;
        z-index: 1;
        width: 10rem; 
        word-wrap: break-word;  
        white-space: normal;  
        overflow: hidden;  
    }
    
</style>
<body>
    <div class="index-page-container">
        <div class="back-button">
            <div class="tooltip-container">
            <%= link_to run_time_objects_path, class: "index-page-button" do %>
            <i class="fas fa-arrow-left"></i> Go Back
            <% end %>
            <span class="tooltip-text">Go back to the container image list page</span>
            </div>
        </div>
        <p class="heading">New Container Image</p>
        <%= form_with model: @run_time_object, url: run_time_objects_path, local: true do |form| %>
            <div class="form-container">
                <div class="form-group">
                    <%= form.label :name, "Name", class: "form-label" %>
                    <%= form.text_field :name, class: "form-control", placeholder: "Value", required: true %>
                </div>
                <div class="form-group">
                    <%= form.label :description, "Description", class: "form-label" %>
                    <%= form.text_field :description, class: "form-control-description", placeholder: "Value", description: nil %>
                </div>
                <div class="actions">
                    <%= form.submit "Create", class: "index-page-button" %>
                </div>
            </div>
        <% end %>
    </div>
    
    <% if @run_time_object.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@run_time_object.errors.count, "error") %> prohibited this image from being saved:</h2>
            <ul>
                <% @run_time_object.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <script>
        document.addEventListener("DOMContentLoaded", function() {  
        const tooltipContainers = document.querySelectorAll('.tooltip-container');
        
        tooltipContainers.forEach(container => {
            let hoverTimeout;
            let tooltip = container.querySelector('.tooltip-text');

            container.addEventListener('mouseenter', () => {
                clearTimeout(hoverTimeout);
                hoverTimeout = setTimeout(() => {
                    tooltip.style.visibility = 'visible';
                    tooltip.style.opacity = '0.85';
                }, 1000); 
            });

            container.addEventListener('mouseleave', () => {
                clearTimeout(hoverTimeout);
                tooltip.style.visibility = 'hidden';
                tooltip.style.opacity = '0';
                });
            });
        });

	</script>
</body>
</html>

app/views/run_time_objects/share.html.erb
<div class="back-button">
    <%= link_to run_time_object_images_path(@run_time_object), class: "index-page-button" do %>
    <i class="fas fa-arrow-left"></i>
    Go Back
    <% end %>
</div>
<div style="text-align: center;">

  <h1>Share Permissions for <%= @run_time_object.name %></h1>


  <%= form_with url: share_with_users_run_time_object_path(@run_time_object), method: :post do |f| %>

    <div style="display: flex; justify-content: center">
      <table style="width: 60%; border-collapse: collapse;">
        <thead>
        <tr>
          <th style="border: 0.1rem solid #ddd; padding: 0.8rem;">User</th>
          <th style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;">View Permission</th>
          <th style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;">Edit Permission</th>
          <th style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;"></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <% if user.id != @run_time_object.user_id && user.first_name.present? && user.last_name.present? %>
            <tr>
              <td style="border: 0.1rem solid #ddd; padding: 0.8rem;">
                <%= "#{user.first_name} #{user.last_name}" %>
              </td>
              <td style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;">
                <%= radio_button_tag "permissions[#{user.id}]", "view", @view_permitted_user_ids.include?(user.id), id: "view_permission_#{user.id}" %>
                <%= label_tag "view_permission_#{user.id}", "" %>
              </td>
              <td style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;">
                <%= radio_button_tag "permissions[#{user.id}]", "edit", @edit_permitted_user_ids.include?(user.id), id: "edit_permission_#{user.id}" %>
                <%= label_tag "edit_permission_#{user.id}", "" %>
              </td>
              <td style="border: 0.1rem solid #ddd; padding: 0.8rem; text-align: center;">
                <%= link_to "Remove Access", "#", class: "remove-access", data: { user_id: user.id } %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
    
    <br>
    <%= submit_tag 'Share', class: 'index-page-button' %>
  <% end %>
</div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        const removeLinks = document.querySelectorAll('.remove-access');

        removeLinks.forEach(link => {
            link.addEventListener('click', function(event) {
                event.preventDefault();
                const userId = this.dataset.userId;
                document.querySelector(`#view_permission_${userId}`).checked = false;
                document.querySelector(`#edit_permission_${userId}`).checked = false;
            });
        });
    });
</script>


<style>
  .btn {
    margin: .5rem;
  }
</style>